
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class Cashier_home extends javax.swing.JFrame {

    /**
     * Creates new form Cashier_home
     */
    public Cashier_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jview = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableview = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jsearch = new javax.swing.JPanel();
        jsearchenter = new javax.swing.JTextField();
        textcate = new javax.swing.JTextField();
        textname = new javax.swing.JTextField();
        textprice = new javax.swing.JTextField();
        textqty = new javax.swing.JTextField();
        bsearchenter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablesearch = new javax.swing.JTable();
        bcategory = new javax.swing.JButton();
        bname = new javax.swing.JButton();
        bprice = new javax.swing.JButton();
        bqty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Narkisim", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CASHIER'S");

        jLabel2.setFont(new java.awt.Font("Narkisim", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAIN MENU");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Product Details");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search Product Details");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, 250, 560));

        jview.setBackground(new java.awt.Color(0, 51, 51));

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableview.setAutoCreateRowSorter(true);
        tableview.setBackground(new java.awt.Color(105, 168, 168));
        tableview.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null)));
        tableview.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        tableview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Fashion", "Handbags", "1250", "19"},
                {"002", "Shopping", "Tote Bags", "950", "22"},
                {"003", "Outdoor", "Backpacks", "1450", "15"},
                {"004", "Fashion", "Crossbody Bags", "2200", "13"},
                {"005", "Sports", "Duffel Bags", "3700", "54"},
                {"006", "Work/Office", "Laptop Bags", "4500", "5"},
                {"007", "Travel", "Sling Bags", "1100", "4"},
                {"008", "Travel", "Travel Bags", "1360", "12"},
                {"009", "Fashion", "Bucket Bags", "1500", "32"},
                {"0010", "Sports", "Golf Bags", "2250", "24"},
                {"0011", "Gym Bags", "Gym Bags", "1750", "10"},
                {"0012", "Travel", "Camera Bags", "1600", "7"},
                {"0013", "Travel", "Beach Bags", "790", "25"},
                {"0014", "Face wash", "Jannet face wash", "450", "50"},
                {"0015", "Body lotion", "Ponds body lotion", "900", "30"}
            },
            new String [] {
                "Product ID", "Categories", "Product name", "Price", "Qty"
            }
        ));
        jScrollPane1.setViewportView(tableview);

        jLabel3.setBackground(new java.awt.Color(112, 211, 211));
        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 179, 179));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("List Of Products");

        jButton5.setBackground(new java.awt.Color(91, 174, 174));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Exit");

        javax.swing.GroupLayout jviewLayout = new javax.swing.GroupLayout(jview);
        jview.setLayout(jviewLayout);
        jviewLayout.setHorizontalGroup(
            jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jviewLayout.createSequentialGroup()
                .addGroup(jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jviewLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jviewLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jviewLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jviewLayout.setVerticalGroup(
            jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jviewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jview);

        jsearch.setBackground(new java.awt.Color(60, 85, 135));

        jsearchenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchenterActionPerformed(evt);
            }
        });

        bsearchenter.setBackground(new java.awt.Color(0, 0, 102));
        bsearchenter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bsearchenter.setForeground(new java.awt.Color(255, 255, 255));
        bsearchenter.setText("Enter Search product");
        bsearchenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchenterActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tablesearch.setBackground(new java.awt.Color(112, 152, 193));
        tablesearch.setForeground(new java.awt.Color(255, 255, 255));
        tablesearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Fashion", "Handbags", "1250", "19", "23750"},
                {"002", "Shopping", "Tote Bags", "950", "22", "20900"},
                {"003", "Outdoor", "Backpacks", "1450", "15", "21750"},
                {"004", "Fashion", "Crossbody Bags", "2200", "13", "28600"},
                {"005", "Sports", "Duffel Bags", "3700", "54", "199,800"},
                {"006", "Work/Office", "Laptop Bags", "4500", "5", "22500"},
                {"007", "Travel", "Sling Bags", "1100", "4", "4400"},
                {"008", "Travel ", "Travel Bags", "1360", "12", "16320"},
                {"009", "Fashion", "Bucket Bags", "1500", "32", "48000"},
                {"0010", "Sports", "Golf Bags", "2250", "24", "54000"},
                {"0011", "Sports", "Gym Bags", "1750", "10", "17500"},
                {"0012", "Travel", "Camera Bags", "1600", "7", "11200"},
                {"0013", "Travel", "Beach Bags", "790", "22", "17380"}
            },
            new String [] {
                "product ID", "Categories", "product name", "Price", "Qty", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablesearch);

        jScrollPane3.setViewportView(jScrollPane2);

        bcategory.setBackground(new java.awt.Color(0, 30, 91));
        bcategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bcategory.setForeground(new java.awt.Color(255, 255, 255));
        bcategory.setText("Category");
        bcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcategoryActionPerformed(evt);
            }
        });

        bname.setBackground(new java.awt.Color(0, 30, 91));
        bname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bname.setForeground(new java.awt.Color(255, 255, 255));
        bname.setText("Name");
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });

        bprice.setBackground(new java.awt.Color(0, 30, 91));
        bprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bprice.setForeground(new java.awt.Color(255, 255, 255));
        bprice.setText("Price");
        bprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpriceActionPerformed(evt);
            }
        });

        bqty.setBackground(new java.awt.Color(0, 30, 91));
        bqty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bqty.setForeground(new java.awt.Color(255, 255, 255));
        bqty.setText("Qty");
        bqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bqtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jsearchLayout = new javax.swing.GroupLayout(jsearch);
        jsearch.setLayout(jsearchLayout);
        jsearchLayout.setHorizontalGroup(
            jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jsearchLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsearchenter, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bsearchenter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jsearchLayout.createSequentialGroup()
                            .addComponent(bcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textcate, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jsearchLayout.createSequentialGroup()
                            .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textname))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jsearchLayout.createSequentialGroup()
                            .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textprice))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jsearchLayout.createSequentialGroup()
                            .addComponent(bqty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textqty))))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jsearchLayout.setVerticalGroup(
            jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jsearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jsearchLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bcategory, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(textcate))
                        .addGap(44, 44, 44)
                        .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bqty)
                            .addComponent(textqty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(jsearchenter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bsearchenter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("tab3", jPanel7);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, -44, -1, 590));

        setSize(new java.awt.Dimension(1394, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Are you sure You want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            Home blogout = new Home();
            blogout.setVisible(true);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Are you sure You want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Are you sure You want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            Home blogout = new Home();
            blogout.setVisible(true);

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jsearchenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchenterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jsearchenterActionPerformed

    private void bsearchenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchenterActionPerformed
        // TODO add your handling code here:
        DefaultTableModel object = (DefaultTableModel)tablesearch.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(object);
        tablesearch.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jsearchenter.getText()));

    }//GEN-LAST:event_bsearchenterActionPerformed

    private void bcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcategoryActionPerformed
       DefaultTableModel object = (DefaultTableModel)tablesearch.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(object);
        tablesearch.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(textcate.getText()));
    }//GEN-LAST:event_bcategoryActionPerformed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
      DefaultTableModel object = (DefaultTableModel)tablesearch.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(object);
        tablesearch.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(textname.getText()));
    }//GEN-LAST:event_bnameActionPerformed

    private void bpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpriceActionPerformed
        DefaultTableModel object = (DefaultTableModel)tablesearch.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(object);
        tablesearch.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(textprice.getText()));
    }//GEN-LAST:event_bpriceActionPerformed

    private void bqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bqtyActionPerformed
        DefaultTableModel object = (DefaultTableModel)tablesearch.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(object);
        tablesearch.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(textqty.getText()));
    }//GEN-LAST:event_bqtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcategory;
    private javax.swing.JButton bname;
    private javax.swing.JButton bprice;
    private javax.swing.JButton bqty;
    private javax.swing.JButton bsearchenter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jsearch;
    private javax.swing.JTextField jsearchenter;
    private javax.swing.JPanel jview;
    private javax.swing.JTable tablesearch;
    private javax.swing.JTable tableview;
    private javax.swing.JTextField textcate;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textprice;
    private javax.swing.JTextField textqty;
    // End of variables declaration//GEN-END:variables
}
